# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    uses: kube-the-home/github-actions/.github/workflows/dotnet-build-test.yaml@962260b6048afd17325015c372eeb835a04b25b2 # v1.4.2
