# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    uses: kube-the-home/github-actions/.github/workflows/dotnet-build-test.yaml@cc715d5c26c3498c970eb730b01344aa61c5152d # v1.3.4
