# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    uses: kube-the-home/github-actions/.github/workflows/dotnet-build-test.yaml@6a42c4b92ae30747603d0846aad29a463f0ea11e # v1.4.3
