name: Release to NuGet

on:
  release:
    types: [published]

jobs:
  release:
    uses: kube-the-home/github-actions/.github/workflows/dotnet-nuget-release.yaml@fa45770cb91e92acf4b3b38347db2afab222a2f8 # v1.4.9
    secrets:
      nuget_api_key: ${{ secrets.nuget_api_key }}
