name: Release to NuGet

on:
  release:
    types: [published]

jobs:
  release:
    uses: kube-the-home/github-actions/.github/workflows/dotnet-nuget-release.yaml@84c1860e25ca085e075b72749337455d6b3ed16c # v1.3.0
    secrets:
      nuget_api_key: ${{ secrets.nuget_api_key }}
